### PR TITLE
Rename all necessary modules, directives and components

### PR DESCRIPTION
**Pull request by ddincheva**

### CODE REVIEW

**Comment by zdrawku** [comment]
I am approving this despite the falling travic-ci build, the errors are related to the changes of Ignite UI for Angular repot that are not yet merged. Once they are merged, the travis-ci build will pass succesfully.

**Comment by kdinev** [comment]
@zdrawku Please link the related PRs to the main pull request in `igniteui-angular`

**Comment by zdrawku** [comment]
Once we tag official version we are going to complete this pull request.

**Comment by ddincheva** [comment]
All applied changes are already merged in IgniteUI:rename-modules. 
https://github.com/IgniteUI/igniteui-angular-samples/pull/65

**Pull request closed without merging**
