### PR TITLE
chore(*): 17 update 

### PR DESCRIPTION
**Pull request by Lipata**

### CODE REVIEW

**Comment by Lipata** [comment]
@simeonoff, @SisIvanova  if you try `ng update @angular/material --next` on this PR, you will get the following error: 
image

I was not able to update even with `--force`.

**Comment by Lipata** [comment]
@simeonoff, one more thing: on build some of the samples are having the following error: 
image

**Comment by simeonoff** [comment]
> @simeonoff, @SisIvanova if you try `ng update @angular/material --next` on this PR, you will get the following error: image
> 
> I was not able to update even with `--force`.

@SisIvanova Can you take a look at this? Can we migrate the material sample to version 17?

**Comment by Lipata** [comment]
Closing it in favour of: https://github.com/IgniteUI/igniteui-angular-samples/pull/3402

**Pull request closed without merging**
