### PR TITLE
Refactor Drag dialog sample

### PR DESCRIPTION
**Pull request by mddragnev**
Related issue: #1681

### CODE REVIEW

**Comment by MayaKirova** [comment]
Looks OK with the default themes. Once there are contrast colors exposed (https://github.com/IgniteUI/igniteui-angular/issues/6539)  we may be able to also change the text color to a contrasting one since the theme widget allows changing the surface color and it is possible to set it so the text is no longer visible, for example:
image

**Comment by ChronosSF** [comment]
> Looks OK with the default themes. Once there are contrast colors exposed ([IgniteUI/igniteui-angular#6539](https://github.com/IgniteUI/igniteui-angular/issues/6539)) we may be able to also change the text color to a contrasting one since the theme widget allows changing the surface color and it is possible to set it so the text is no longer visible, for example:
> image

@MayaKirova , @3phase , we could wait for the contrast colors mixin but only if it is based on the surface color, which I think it is not.

**Comment by 3phase** [comment]
> > Looks OK with the default themes. Once there are contrast colors exposed ([IgniteUI/igniteui-angular#6539](https://github.com/IgniteUI/igniteui-angular/issues/6539)) we may be able to also change the text color to a contrasting one since the theme widget allows changing the surface color and it is possible to set it so the text is no longer visible, for example:
> > image
> 
> @MayaKirova , @3phase , we could wait for the contrast colors mixin but only if it is based on the surface color, which I think it is not.

The PR [IgniteUI/igniteui-angular#6539](https://github.com/IgniteUI/igniteui-angular/issues/6559) exposes a mixin, that generates a contrast-color property for all the colors and their shades, so it might resolve the unreadable text color in this pull request as well.

**Comment by ChronosSF** [comment]
Awaiting the contrast color adjustments.

**Pull request merged**
