### PR TITLE
Created a drag and drop sample.

### PR DESCRIPTION
**Pull request by MartinKamenov**

### CODE REVIEW

**Comment by mpavlinov** [comment]
@MartinKamenov I think it will be better to have the images shuffled in the main grid and the user just need to re-arrange them.

**Comment by StefanIvanov** [comment]
> @MartinKamenov I think it will be better to have the images shuffled in the main grid and the user just need to re-arrange them.

This is very accurate, especially since the grid below is implemented with 9 dragdrop areas and we show dragging from one area to another. However to make such a puzzle work we'd need to leave on piece of the picture out to always provide and area to drop to.

**Comment by mpavlinov** [comment]
@MartinKamenov The functionality looks good to me. The only issue I see are the borders of the tiles. You need to have only 1px border across the puzzle. Not it's not consistent.

**Comment by mpavlinov** [comment]
@MartinKamenov Also, please use a dialog for the "congratulations" message.

**Comment by mpavlinov** [comment]
We also need to add a StackBlitz configuration. I'll add it.

**Pull request merged**
