### PR TITLE
Sample demonstrating how to save and load the igxGrid state

### PR DESCRIPTION
**Pull request by hanastasov**
Part of #890

### CODE REVIEW

**Comment by nrobakova** [comment]
I have tested the sample and there are some issues:
1. When for a column select 2 filters with operand AND, and reload the page the operand is changed to OR
2. When for a column select 2 filters with operand OR, only the first filter is saved after reload
3. When for column Register Date filter with date, after reload this date is not in correct format
4. When selection is checked only row selection is saved, but cell selection is not.

**Comment by zdrawku** [comment]
@hanastasov, I found the following issues below:
- filtering type is "string" for all columns
- after clearing the localStorage, the state is persisted again, while navigation to About page and back, or by refreshing the page with the refresh button

**Comment by hanastasov** [comment]
> @hanastasov, I found the following issues below:
> 
> * filtering type is "string" for all columns --> fixed with latest push
> * after clearing the localStorage, the state is persisted again, while navigation to About page and back, or by refreshing the page with the refresh button --> state is being saved at the moment you navigate away. This is why afetr clearing the storage, use the reload button to reload the page with clear state.

**Comment by nrobakova** [comment]
@hanastasov can you look at this issues:
1. Can you change the checkbox Selection to Row Selection, because it may be clear that only the row selection is saved.
2. When I select a row, filter with no values, leave page and return to it, the row selector header is checked, but it should not be.

**Comment by hanastasov** [comment]
Please test the Stackblitz config.

**Pull request merged**
