### PR TITLE
Add dock manager config generator

### PR DESCRIPTION
**Pull request by onlyexeption**

### CODE REVIEW

**Comment by DiyanDimitrov** [comment]
@onlyexeption, Could you please replace the private licensed package with the [npmjs one](https://www.npmjs.com/package/igniteui-dockmanager) and check if the stackblitz sample works as expected?

**Comment by HristoP96** [comment]
@onlyexeption  @DiyanDimitrov  I added the dock manager to the additional dependencies of the config, however, the Stackblitz bundle is not loading the package after the the bundles instantiation, this may be due the beta version of the package

**Comment by HristoP96** [comment]
@DiyanDimitrov @onlyexeption There must be applied additional logic in the live-editing generator, due the additional requirements that dock manager needs in order to work properly, like define elements in the main.ts and adding schemas property in the ngModule in app module.ts.

**Comment by HristoP96** [comment]
I will let you know when I am ready with the live editing update

**Pull request merged**
