### PR TITLE
Add Styling to Chip Samples

### LINKED ISSUE #1415: Add Styling to Chip Samples
Related: IgniteUI/igniteui-docfx#1275

### PR DESCRIPTION
**Pull request by 3phase**
Closes #1415

### CODE REVIEW

**Comment by VMihalkov** [comment]
My comments:

1. $border-radius is missing from the code snippets, but is included in the igx-chip-theme in the sample
2. styling could be added for $hover-selected-text-color too
3. "respctive" typo in last sentence from Schemas

**Comment by 3phase** [comment]
> My comments:
> 
> 1. $border-radius is missing from the code snippets, but is included in the igx-chip-theme in the sample
> 2. styling could be added for $hover-selected-text-color too
> 3. "respctive" typo in last sentence from Schemas

Done

**Comment by zdrawku** [comment]
@3phase and @VMihalkov the build is failing with "ERROR in Cannot determine the module for class EmailFilterPipe in /home/vsts/work/1/s/src/app/data-display/chip-styling/chip-styling.component.ts! Add EmailFilterPipe to the NgModule to fix it." Could you take a look

**Comment by 3phase** [comment]
> @3phase and @VMihalkov the build is failing with "ERROR in Cannot determine the module for class EmailFilterPipe in /home/vsts/work/1/s/src/app/data-display/chip-styling/chip-styling.component.ts! Add EmailFilterPipe to the NgModule to fix it." Could you take a look

Done 🤜🤛

**Pull request merged**
