### PR TITLE
Check-in for conditional formatting, configuring, and activation sample.

### PR DESCRIPTION
**Pull request by agoldenbaum**

### CODE REVIEW

**Comment by zdrawku** [comment]
As we discussed with @pamelabrasil, we are not going to merge PRs related to Charts, Gauges and Spredsheets for the time being. Once we promote current version of staging to prod I will remove `do not merge` label.

**Comment by pamelabrasil** [comment]
pushed to production, removing do not merge label and merging

**Comment by zdrawku** [comment]
We need to push again today, because we found some failing samples. @mpavlinov

**Comment by pamelabrasil** [comment]
@zdrawku did you guys push to production?

**Comment by zdrawku** [comment]
Yes Pamela, removing all "do not merge" labels

**Pull request merged**
