### PR TITLE
Changes Email Sample List to igxList - master

### PR DESCRIPTION
**Pull request by 3phase**
Related issue: #1681

### CODE REVIEW

**Comment by MayaKirova** [comment]
I see a few minor issues:
1) Active list item style is lost on hover when dark theme is applied.
2) The drag item ghost is not styled according to the theme: 
image
3) Active style is not applied when item is selected in IE.

**Comment by 3phase** [comment]
> I see a few minor issues:
> 
> 1. Active list item style is lost on hover when dark theme is applied.
> 2. The drag item ghost is not styled according to the theme:
>    image
> 3. Active style is not applied when item is selected in IE.
> 4. Current background color is blue on both light and dark theme, perhaps it would be better to use the grid's selection style instead as it uses the secondary color:
>    background-color: var(--igx-grid-row-selected-background);

@MayaKirova, thank you for the remarks, I resolved them.

**Comment by MayaKirova** [comment]
@3phase Could you also apply the changes to the vnext PR - https://github.com/IgniteUI/igniteui-angular-samples/pull/1682

**Comment by 3phase** [comment]
> @3phase Could you also apply the changes to the vnext PR - #1682

Done.

**Comment by ChronosSF** [comment]
At this point it's too late to make master-specific fixes.

**Pull request closed without merging**
