### PR TITLE
Change the theme applied to samples

### LINKED ISSUE #131: Introduce a color picker for changing the primary and secondary colors in a sample
### Description  
Introduce a color picker for changing the primary and secondary colors in a sample. I want to see the theming customization live in a sample, where I can pick two new colors and the sample responds.

### PR DESCRIPTION
**Pull request by hanastasov**
Closes #131

### CODE REVIEW

**Comment by hanastasov** [comment]
This PR will include more commits with the predefined themes that user can select.

**Comment by HristoP96** [comment]
I made a branch and named it like yours and pushed my changes.

**Comment by zdrawku** [comment]
@desig9stein what should be the colors of the buttons:

image

**Comment by desig9stein** [comment]
> @desig9stein what should be the colors of the buttons:
> 
> image

The colour for the two boxes should be, 
Default - primary:#09f, secondary:#e41c77
Dark - primary:#09f, secondary:#72da67.

**Pull request merged**
