### PR TITLE
Add pivot state persistance sample

### PR DESCRIPTION
**Pull request by mddragnev**

### CODE REVIEW

**Comment by MayaKirova** [comment]
@mddragnev 
The "Go Back" button does not work, it seems that it has a different url that does not match the sample:
Cannot match any routes. URL Segment: 'samples/pivot-grid/pivot-grid-state-persistance'

**Comment by mddragnev** [comment]
@MayaKirova 
Both things should be okay now. Do you think that we need to remove row selection from the topic as well, or save it there and just fix the issue?

**Comment by MayaKirova** [comment]
@mddragnev think it can stay and we can enable it back in the sample once the issue is fixed.

**Review by tishko0 — APPROVED** [review]

**Comment by mddragnev** [comment]
> 

@dkamburov I do not encounter that error. On my machine everything works fine. I have removed node_modules and reinstalled them. Both of the samples load correctly in the docfx.

**Comment by dkamburov** [comment]
I could've had some leftovers in the local storage

**Pull request merged**
