### PR TITLE
sample added: grid move column style

### PR DESCRIPTION
**Pull request by VladB93**
Related to docfx [#1275](https://github.com/IgniteUI/igniteui-docfx/issues/1275)

### CODE REVIEW

**Comment by HristoP96** [comment]
A new version with this fix - [https://github.com/IgniteUI/igniteui-angular/issues/5137](https://github.com/IgniteUI/igniteui-angular/issues/5137) should be released, in order the samples could style the column moving headers correctly. Until then, it will be better to not merge PR

**Comment by kdinev** [comment]
@VladB93 @HristoP96 The fix is now available in 8.0.2, so this should be ready to merge with the update of the packages?

**Comment by HristoP96** [comment]
> @VladB93 @HristoP96 The fix is now available in 8.0.2, so this should be ready to merge with the update of the packages?

@kdinev I think this should be merged after the update of the packages, because the ViewChild decorators should be changed for Angular 8 compatibility.

**Comment by zdrawku** [comment]
@VladB93 the PR with angular 8 upgrade was just merged to master, you can proceed with the ViewChild decorators changes

**Pull request merged**
