### PR TITLE
chore(*): update 17

### PR DESCRIPTION
**Pull request by Lipata**

### CODE REVIEW

**Comment by zdrawku** [comment]
@Lipata, @dobromirts is aware of the problem with the live-editing build, he will submit a fix shortly and re-test

**Comment by zdrawku** [comment]
Actually, the problem comes from the library itself, as @ChronosSF pointed out "We should either add a migration for this, add it in the migration guide or make the parameter optional, if possible"

**Comment by kdinev** [comment]
@zdrawku I will update the live-editing.

**Comment by zdrawku** [comment]
We can start testing on staging once the PR is merged

**Review by ChronosSF — APPROVED** [review]

**Pull request merged**
