### PR TITLE
xsharp - fixed missing modules in DC stackblitz

### PR DESCRIPTION
**Pull request by HUSSAR-mtrela**
- fixed DC modules in stackblitz
- excluded unfinished DC samples from SB's navigation tree

### CODE REVIEW

**Comment by gmurray81** [comment]
@HUSSAR-mtrela what's the rationale behind the commented out stuff? Things being removed? Or refactored?

**Comment by HUSSAR-mtrela** [comment]
@gmurray81 I commented out samples in navigation tree because they were not finished and they were showing up as  blank pages.

**Comment by zdrawku** [comment]
Hey Viktor, these changes may have positive impact on issues #1063 #1064 #1066

**Comment by valadzhov** [comment]
> 
> 
> Hey Viktor, these changes may have positive impact on issues #1063 #1064 #1066

Thanks, @zdrawku! I tried the changes but sadly they don't these issues.

**Comment by zdrawku** [comment]
As we discussed with @pamelabrasil, we are not going to merge PRs related to Charts, Gauges and Spredsheets for the time being. Once we promote current version of staging to prod I will remove `do not merge` label.

**Pull request merged**
