### PR TITLE
ci(*): create codeql.yml

### PR DESCRIPTION
**Pull request by kdinev**

### CODE REVIEW

**Comment by zdrawku** [comment]
@kdinev please rebase or cherry-pick your changes against vNext branch

**Comment by kdinev** [comment]
@zdrawku I see there's changes in `master` that are not in `vNext`. Why is that?

**Comment by zdrawku** [comment]
I guess we've not been following the process of bug/feature implementation that strictly. I will have to check that with the teams and remind them the difference between `vNext` and `master`.


image

**Comment by kdinev** [comment]
@zdrawku The PR is to `vNext` and it's evening vNext with `master`

**Review by zdrawku — APPROVED** [review]

**Pull request merged**
