### PR TITLE
DV angular8 update

### PR DESCRIPTION
**Pull request by mddifilippo89**
DV Angular 8 Update

### CODE REVIEW

**Comment by HUSSAR-mtrela** [comment]
@mddifilippo89 why is your PR targeting "IGanchev/update-static-master" branch?

**Comment by mddifilippo89** [comment]
@HUSSAR-mtrela 
I was told by Zdravko, to create a new PR and update his branch before going to master.

**Comment by Lipata** [comment]
@HUSSAR-mtrela the IGanchev/update-static-master is the branch that contains the updates for all controls, excluding DV components. So this is the correct target branch. However @mddifilippo89 I see a lot of commits that are not related to your changes or the one of @IvayloG. Did you start applying your changes by switching first to IGanchev/update-static-master branch?

**Comment by mddifilippo89** [comment]
@Lipata 
Let me know what should be removed. I had a little trouble getting just the angular 8 stuff in one PR.

**Comment by Lipata** [comment]
What could be the most painless solution would be to create a new branch, starting from the latest version of IGanchev/update-static-master branch, and then cherry-pick each of your individual commits, related only the DV samples. I see this [commit](https://github.com/IgniteUI/igniteui-angular-samples/pull/1200/commits/5350ee2510fb508b0792644d33da79b97e94206f) as the initial one, right? Pick this commit and all others related to the Angular 8 update and cherry-pick them in the new branch and then create a new pull request. After that, you will close this pull request.

**Comment by Lipata** [comment]
The [changes](https://github.com/IgniteUI/igniteui-angular-samples/pull/1185) are applied with this pull request.

**Pull request closed without merging**
